project: "ADR_mission_planning"
program: wandb_sweep.py
method: grid
metric:
  name: avg_reward
  goal: maximize
parameters:
  tau:
    values: [0.001, 0.01, 0.1, 10]
  learning_rate:
    values: [0.00001, 0.0001, 0.001, 0.01]
  gamma:
    values: [0.99, 0.999, 0.9999]
  minibatch_size:
    values: [8, 16, 32, 64]
  replay_updates_per_step:
    values: [2, 4, 6, 8]
  replay_buffer_size:
    values: [250000, 5000000, 1000000, 2000000]
  seed:
    values: [0, 1, 2]

# too costly to run